### ISSUE TITLE
Character Filter and Autofocus not working?

### ISSUE THREAD

**Issue by desirlana** [Elckarow/Autofocus-old-#10]
It works normally when I include multiple character but when its a character by itself it doesn't work? Is this by default and if so is there a way I can change that? Like I want the character to be able to still change focus where dialogue changes between the player and character.

**Comment by Elckarow** [comment]
yes this is the default behavior _(although i plan on changing that in the next update (if it ever comes out))_

open `01AutofocusStore.rpy` and set `autofocus_interpolation_minimum_char_requirement` to `1`
